services:
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - smash-recap-minio:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY}
    command: server /data --console-address ":9001"

  minio-setup:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (mc alias set myminio http://minio:9000 ${S3_ACCESS_KEY_ID} ${S3_SECRET_ACCESS_KEY}); do echo '...waiting for minio...'; sleep 1; done;
      mc mb myminio/smash-recap --ignore-existing;
      mc anonymous set public myminio/smash-recap;
      mc ilm add --expiry-days 7 myminio/smash-recap;
      exit 0;
      "

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - smash-recap-redis:/data

volumes:
  smash-recap-minio:
  smash-recap-redis:
