services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - smashrecap-redis:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis

volumes:
  smashrecap-redis:
